### ISSUE TITLE
Bug in objectosphere code?

### ISSUE THREAD

**Issue by siebenkopf** [Vastlab/vast#45]
I am afraid that the current implementation of the objectosphere loss does effectively nothing. The reason for this is that you `detach` from the gradient here: https://github.com/Vastlab/vast/blob/b4afe193b2f7c079c35bfc1985f84ae464ff3ff3/vast/losses/losses.py#L150
in order to compute the magnitude that is finally used to define the loss. This means that the loss does not participate in the backward pass and, thus, no weights are updated when using this loss.

Is there any particular reason why this is done?

**Comment by akshay-raj-dhamija** [comment]
you are right, it seems this was added in the following commit which seems to have code in the middle of debugging.
https://github.com/Vastlab/vast/commit/c4dd743d8443b578e3c58d85f5022f9addafd5e1?diff=split
PR #47 should address this.

Effectively, when objectosphere was being used with entropic open-set loss, while the loss being reported was correct, the weights being learnt were only based on entropic open-set loss. Weirdly after fixing this issue I see no difference in the MNIST result, not sure why.

**Comment by siebenkopf** [comment]
My believe is that the MNIST example is too simple and that in the 2D space there is little need for the objectosphere part of the loss. Due to the bottleneck, unknown features are automatically pushed to the center -- there is no other simple way. Consequently, the plots look very similar. 
In more complex examples with deep features including more dimensions, it seems that the entropic loss alone does not automatically lead to unknown features gathering around 0. Hence, the magnitude plot (such as in the Innocent paper) does not work any more. Hopefully, this fix will help in this case again (I have a meeting with one of my students soon who is currently working on an extension of that paper).

**Comment by akshay-raj-dhamija** [comment]
Thankyou Manuel (@siebenkopf) for pointing this out. The fix has been merged.
