### ISSUE TITLE
Broken link for MNIST features in the example notebook

### ISSUE THREAD

**Issue by ggalan87** [Vastlab/vast#56]
Hello, the [link](http://dhamija.me/mnist_features/train_mnist.csv) for the features from MNIST dataset that can be found inside the [example notebook](https://github.com/Vastlab/vast/blob/main/vast/opensetAlgos/Example.ipynb) is broken, probably due to expired URL. 

@akshay-raj-dhamija can you provide another way to get the features or give an indication about what does the CSVs contain? As I see there are two keywords, 'Features1', 'Features2'. Are these 2D features obtained from some dimensionality reduction method, or just 2 arbitrary features?

**Comment by akshay-raj-dhamija** [comment]
Thanks for bringing this to my attention. The links have been replaced in the notebook, it should work now.
The features are the output of the 'fc1' layer of a [LeNet++ network](https://github.com/Vastlab/vast/blob/main/vast/architectures/architectures.py#L5) trained to classify MNIST digits.
