### ISSUE TITLE
tail size computation for relative batch sizes in EVM is wrong

### ISSUE THREAD

**Issue by siebenkopf** [Vastlab/vast#57]
There are two ways of providing a batch size for EVM training: absolute (int > 1) and relative (float <= 1.).

When using relative numbers, they should be relative to the number of negative samples. Unfortunately, in the EVM implementation they are relative to the number of positive samples:
https://github.com/Vastlab/vast/blob/e74b0c99a559832df212afb8f065758796b27924/vast/opensetAlgos/EVM.py#L199
https://github.com/Vastlab/vast/blob/e74b0c99a559832df212afb8f065758796b27924/vast/opensetAlgos/EVM.py#L261

**Comment by akshay-raj-dhamija** [comment]
Yes, you are right. I had kept it the same as we do for OpenMax, which is incorrect for EVM.
The reason for doing so was that the current EVM is very very inefficient for large tail sizes, this is another issue for which I am open to suggestions.

Also if you are looking to train EVM or any of the other weibull based methods for large datasets like ImageNet you might find [this repo](https://github.com/akshay-raj-dhamija/vel/tree/main/Feature_Distribution) useful.

Thanks for the fix!
